import { createHash } from 'node:crypto';
import type {
  AssuranceState,
  ChangeSurface,
  CheckDocument,
  ChangedFileStatus,
  MigrationExecutionObservation,
  MigrationExecutionStage,
  MigrationExecutionSubject,
  RequirementId,
  StageStatus,
  Verdict,
} from '@assurance-compiler/core';

/**
 * Version of the cloud payload. Every field below is on the allowlist deliberately; anything a
 * local run knows that is not listed here (database messages, stage details, tool output,
 * evidence summaries, assessment reasons, leftover paths, SQL, fixtures) never leaves the
 * machine. Incompatible changes increment this number.
 */
export const CLOUD_REPORT_VERSION = 1;

/** A stage transition without its free-form detail. */
export interface CloudStage {
  readonly name: MigrationExecutionStage;
  readonly status: StageStatus;
  readonly startedAt?: string;
  readonly durationMs?: number;
}

/**
 * The verification record a CLI may report. Identities (commits, blob IDs, seed path,
 * migration names, table names) are disclosed repository metadata: they are named in the
 * linking disclosure and can themselves be sensitive.
 */
export interface CloudVerification {
  readonly runId: string;
  readonly provider: { readonly id: string; readonly version: string };
  readonly environment: { readonly postgres?: string; readonly prisma?: string };
  readonly subject: MigrationExecutionSubject;
  readonly stages: readonly CloudStage[];
  readonly populatedTables: readonly { readonly table: string; readonly populated: boolean }[];
  /** The failing migration and SQLSTATE only. The database message stays local. */
  readonly migrationFailure?: { readonly migration: string; readonly sqlState: string };
  /** Leftover resources are local absolute paths, so only their number is reported. */
  readonly cleanup: { readonly status: 'succeeded' | 'failed'; readonly leftoverCount: number };
}

export interface CloudRunReport {
  readonly version: typeof CLOUD_REPORT_VERSION;
  /** Equals the verification run ID when verification ran; otherwise generated by the CLI. */
  readonly runId: string;
  readonly cli: { readonly version: string };
  readonly startedAt: string;
  readonly finishedAt: string;
  readonly base: { readonly ref: string; readonly commit: string };
  readonly head: { readonly ref: string; readonly commit: string };
  readonly mergeBase: string;
  readonly detectors: readonly string[];
  readonly changes: readonly {
    readonly surface: ChangeSurface;
    readonly detector: string;
    readonly files: readonly {
      readonly path: string;
      readonly status: ChangedFileStatus;
      readonly previousPath?: string;
    }[];
  }[];
  /** Requirement states only. Reasons and summaries are regenerated from structured fields. */
  readonly requirements: readonly {
    readonly id: RequirementId;
    readonly state: AssuranceState;
    readonly triggeredBy: readonly ChangeSurface[];
  }[];
  readonly verdict: Verdict;
  readonly verification: CloudVerification | null;
  /** Hash of the complete local evidence file, when one was written, for provenance. */
  readonly localArtifact?: { readonly sha256: string };
}

/** A progress event: one stage transition, ordered per run by `sequence` starting at 1. */
export interface CloudRunEvent {
  readonly version: typeof CLOUD_REPORT_VERSION;
  readonly runId: string;
  readonly sequence: number;
  readonly at: string;
  readonly stage: CloudStage;
}

export interface ProjectionContext {
  readonly runId: string;
  readonly cliVersion: string;
  readonly startedAt: string;
  readonly finishedAt: string;
  readonly localArtifactSha256?: string;
}

/** Projects a local check document onto the allowlist. Nothing else is copied. */
export function projectCheckDocument(
  document: CheckDocument,
  context: ProjectionContext,
): CloudRunReport {
  return {
    version: CLOUD_REPORT_VERSION,
    runId: context.runId,
    cli: { version: context.cliVersion },
    startedAt: context.startedAt,
    finishedAt: context.finishedAt,
    base: { ref: document.base.ref, commit: document.base.commit },
    head: { ref: document.head.ref, commit: document.head.commit },
    mergeBase: document.mergeBase,
    detectors: [...document.detectors],
    changes: document.changes.map((change) => ({
      surface: change.surface,
      detector: change.detector,
      files: change.files.map((file) =>
        file.status === 'renamed'
          ? { path: file.path, status: file.status, previousPath: file.previousPath }
          : { path: file.path, status: file.status },
      ),
    })),
    requirements: document.requirements.map((requirement) => ({
      id: requirement.id,
      state: requirement.state,
      triggeredBy: [...requirement.triggeredBy],
    })),
    verdict: document.verdict,
    verification:
      document.verification === null ? null : projectVerification(document.verification),
    ...(context.localArtifactSha256 === undefined
      ? {}
      : { localArtifact: { sha256: context.localArtifactSha256 } }),
  };
}

export function projectStage(record: {
  readonly name: MigrationExecutionStage;
  readonly status: StageStatus;
  readonly startedAt?: string;
  readonly durationMs?: number;
}): CloudStage {
  return {
    name: record.name,
    status: record.status,
    ...(record.startedAt === undefined ? {} : { startedAt: record.startedAt }),
    ...(record.durationMs === undefined ? {} : { durationMs: record.durationMs }),
  };
}

function projectVerification(observation: MigrationExecutionObservation): CloudVerification {
  const { subject } = observation;
  return {
    runId: observation.runId,
    provider: { id: observation.provider.id, version: observation.provider.version },
    environment: {
      ...(observation.environment.postgres === undefined
        ? {}
        : { postgres: observation.environment.postgres }),
      ...(observation.environment.prisma === undefined
        ? {}
        : { prisma: observation.environment.prisma }),
    },
    subject: {
      baseline: subject.baseline,
      candidate: subject.candidate,
      schema: { baseline: subject.schema.baseline, candidate: subject.schema.candidate },
      seed: { path: subject.seed.path, blob: subject.seed.blob },
      baselineMigrations: subject.baselineMigrations.map(({ name, blob }) => ({ name, blob })),
      candidateMigrations: subject.candidateMigrations.map(({ name, blob }) => ({ name, blob })),
      expectedTables: [...subject.expectedTables],
    },
    stages: observation.stages.map(projectStage),
    populatedTables: observation.populatedTables.map(({ table, populated }) => ({
      table,
      populated,
    })),
    ...(observation.migrationFailure === undefined
      ? {}
      : {
          migrationFailure: {
            migration: observation.migrationFailure.migration,
            sqlState: observation.migrationFailure.sqlState,
          },
        }),
    cleanup: {
      status: observation.cleanup.status,
      leftoverCount: observation.cleanup.leftovers.length,
    },
  };
}

/**
 * Serializes with keys in sorted order at every level, so the same report always produces the
 * same bytes and the same hash, whichever process built it.
 */
export function canonicalJson(value: unknown): string {
  return JSON.stringify(sortKeys(value));
}

/** The hash of the cloud projection. It is a different document from the local evidence file. */
export function reportHash(report: CloudRunReport): string {
  return createHash('sha256').update(canonicalJson(report)).digest('hex');
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([, entry]) => entry !== undefined)
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([key, entry]) => [key, sortKeys(entry)]),
    );
  }
  return value;
}
